# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9009
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: roxygenize
        # roxygen requires loading pkg -> add dependencies from DESCRIPTION
        additional_dependencies:
        -    gert
        -    gh
        -    glue
        -    precommit
        -    usethis
        -    utils
        -    withr
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    # -   id: spell-check
    #     exclude: >
    #       (?x)^(
    #       data/.*|
    #       (.*/|)\.Rprofile|
    #       (.*/|)\.Renviron|
    #       (.*/|)\.gitignore|
    #       (.*/|)NAMESPACE|
    #       (.*/|)WORDLIST|
    #       (.*/|)\.travis.yml|
    #       (.*/|)appveyor.yml|
    #       (.*/|)\.Rbuildignore|
    #       (.*/|)\.pre-commit-.*|
    #       .*\.[rR]|
    #       .*\.Rproj|
    #       .*\.py|
    #       .*\.feather|
    #       .*\.rds|
    #       .*\.Rds|
    #       .*\.sh|
    #       .*\.RData
    #       )$
    -   id: lintr
        args: [--warn_only]
        verbose: true
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
        args: [--allow_private_imports]
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.0.1
#    hooks:
#    -   id: check-added-large-files
#        args: ['--maxkb=200']
#    -   id: end-of-file-fixer
#        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: r
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
